### ISSUE TITLE
Entity Framework is trying to use a non-existing connection string resulting in a SqlException during user registration at the DemoU2FSite

### ISSUE THREAD

**Issue by tok7886** [brucedog/u2flib#6]
A DbContext constructor that requires a single string parameter is called in DataContext.cs and this causes Entity Framework to try to use a connection string with a name specified by the parameter ("DataContext"). The web.config does not have a connection string with this name, but it has a default one named "DefaultConnection". I found [this MSDN article](https://msdn.microsoft.com/en-us/data/jj592674) and decided to change the string parameter value to either "DefaultConnection" or "name=DefaultConnection". 
 ![sqlexception userrepository cs line75](https://cloud.githubusercontent.com/assets/9751217/8786628/eef359d0-2f37-11e5-973e-e7a5c8228381.png)
![datacontext cs line11](https://cloud.githubusercontent.com/assets/9751217/8786642/05117468-2f38-11e5-9387-ab0daf82ea2a.png)

**Comment by brucedog** [comment]
Connection string has been updated to use DefaultConnection instead of DataContext
